#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/6e92ec6b-3108-4191-a04b-85c291407dca/localhost # baseUri: localhost
title: Content Card Experience API
version: v1
types: 
  contentCards: !include resourceTypes/contentCards.raml
  contentCardPost: !include resourceTypes/contentCardPost.raml
  contentCardPut: !include resourceTypes/contentCardPut.raml
/{id_organization}:
  /content_cards:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: contentCards[]
              example: !include examples/json_files/contentCards.json
    post:
      body: 
        application/json:
          type: contentCardPost
          example: !include examples/json_files/contentCardPost.json
      responses: 
        200:
          body: 
            application/json:
              example: !include examples/json_files/responses/contentCardInserted.json
    /{id_content_card}:
      get:
        responses: 
          200:
            body: 
              application/json:
                type: contentCardPut
                example: !include examples/json_files/contentCardPut.json      
      put:
        body: 
          application/json:
            type: contentCardPut
            example: !include examples/json_files/contentCardPut.json
        responses: 
          200:
            body: 
              application/json:
                example: !include examples/json_files/responses/contenCardUpdated.json            