#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/4d71cd9a-0fa1-4e29-8176-5cdb98220155/localhost # baseUri: localhost 
version: v1
title: Users Experience API
types: 
  User: !include data_types/user.raml
  UserInfo : !include data_types/userInfo.raml
  Users: !include data_types/users.raml  
  target: !include data_types/target.raml
  userAccess: !include data_types/userAccess.raml  
  userRole: !include data_types/userRole.raml
/users:     
  get:
    queryParameters:
      id_organization?: 
        type: string
        description: Fecth users by organization (Filter)
    description: Get all users from
    responses: 
      200:
        body: 
          application/json:
            type: Users[]
            example: !include examples/json_files/users.json
  post:
    description: Create a new user
    body: 
      application/json:
        type: User
        example: !include examples/json_files/user_post.json
    responses: 
      200:
        body: 
          application/json:
            example: !include examples/json_files/responses/user_created.json
  /{id_user}:
    get:
      description: Get an users by Id
      responses: 
        200:
          body: 
            application/json:
              type: User
              example: !include examples/json_files/user.json
    put:
      description: Update a user
      body: 
        application/json:
          type: User
          example: !include examples/json_files/user.json
      responses: 
        200:
          body: 
            application/json:
              example: !include examples/json_files/responses/user_updated.json
  /access:
    /info:
      /{id_user}:
        get:
          responses:
            200: 
              body:   
                application/json:
                  type: UserInfo
                  example: !include examples/json_files/user_info.json
    post:
      body: 
        application/json:
          type: userAccess
          example: !include examples/json_files/user_access.json
      responses: 
        200:
          body: 
            application/json:
              example: !include examples/json_files/user_access_response.json
  /roles:
    get:
      description: Get all users roles
      responses: 
        200:
          body: 
            application/json:
              type: userRole[]
              example: !include examples/json_files/user_roles.json
    post:
      description: Created a new user role
      body: 
        application/json:
          type: userRole
          example: !include examples/json_files/user_role.json
      responses: 
        201:
          body: 
            application/json:
              example: !include examples/json_files/responses/user_role_created.json
    /{id_user_role}:
      get:
        description: Get an user role by Id
        responses: 
          200:
            body: 
              application/json:
                type: userRole
                example: !include examples/json_files/user_role.json
      put:
        description: Update an user role by Id
        body: 
          application/json:
            type: userRole
            example: !include examples/json_files/user_role.json
        responses: 
          200:
            body: 
              application/json:
                example: !include examples/json_files/responses/user_role_created.json
  /target: 
    get:
      queryParameters: 
        id_target?: 
          type: string
          description: fecth user target
        id_organization?:
          type: string
          default: fetch target reached by organization (filter)
        id_content_card?:
          type: string
          default: fetch target reached by content card (filter)
      responses: 
        200:
          body: 
            application/json:
              example: !include examples/json_files/users_target.json     
    post:
      description: Create a new user target
      body: 
        application/json:
          type: target
          example: !include examples/json_files/user_target.json
      responses: 
        201:
          body: 
            application/json:
              example: !include examples/json_files/responses/user_created.json   