#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/8345621d-5d9e-46ce-b810-bc67c0cd2816 # 
title: Beacon System API
version: v1
types:
  beacon: !include resourceTypes/beacon.raml
  beaconType: !include resourceTypes/beacon_type.raml
  beaconHierarchy: !include resourceTypes/beacon_hierarchy.raml
  beaconPlaceHierarchyUpdate: !include resourceTypes/beacon_place_hierarchy_put.raml
  beaconPlaceHierarchies: !include resourceTypes/beacon_place_hierarchy.raml
/beacons:
  get:
    description: Get All Beacon
    responses:
      200:
        body:
          application/json:
            type: beacon[]
            example: !include examples/json_files/beacons.json
  /{id_organization}:
    get:
      description: Get All Beacon by Organization
      responses:
        200:
          body:
            application/json:
              type: beacon[]
              example: !include examples/json_files/beacons.json
    /{id_beacon}:
      get:
        description: Get a Beacon
        responses:
          200:
            body:
              application/json:
                type: beacon
                example: !include examples/json_files/beacon.json
      put:
        description: Update a Beacon
        body:
          application/xml:
            schema: !include schemas/beacon.xsd
            example: !include examples/xml_files/beacon.xml
    /type:
      get:
        description: Get All Beacons Types
        responses:
          200:
            body:
              application/json:
                type: beaconType[]
                example: !include examples/json_files/beaconTypes.json
      post:
        description: Register a Beacon Type
        body:
          application/xml:
            schema: !include schemas/beaconType.xsd
            example: !include examples/xml_files/beaconType.xml
      /{id_beacon_type}:
        get:
          description: Get a Beacon Type
          responses:
            200:
              body:
                application/json:
                  type: beaconType
                  example: !include examples/json_files/beaconType.json
        put:
          description: Update a Beacon Type
          body:
            application/xml:
              schema: !include schemas/beaconType.xsd
              example: !include examples/xml_files/beaconType.xml
          responses:
            200:
              body:
                application/json:
    /hierarchy:
      post:
        description: Register a Beacon Type
        body:
          application/xml:
            schema: !include schemas/beaconHierarchy.xsd
            example: !include examples/xml_files/beaconHierarchy.xml

      get:
        description: Get All Beacons Hierarchies
        responses:
          200:
            body:
              application/json:
                type: beaconHierarchy[]
                example: !include examples/json_files/beaconHierarchies.json
      /{id_beacon_hierarchy}:
        get:
          description: Get a Beacon Hierarchy
          responses:
            200:
              body:
                application/json:
                  type: beaconHierarchy
                  example: !include examples/json_files/beaconHierarchy.json
        put:
          description: Update a Beacon Hierarchy
          body:
            application/xml:
          responses:
            200:
              body:
                application/xml:
                  schema: !include schemas/beaconHierarchy.xsd
                  example: !include examples/xml_files/beaconHierarchy.xml
    /place_hierarchy:
      get:
        description: Get All Beacons Place Hierarchy
        responses:
          200:
            body:
              application/json:
                type: beaconPlaceHierarchies[]
                example: !include examples/json_files/beaconsPlaceHierarchies.json
      /{id_beacon_place_hierarchy}:
        put:
          description: Update a Beacon Place Hierarchy
          body:
            application/xml:
              schema: !include schemas/beaconPlaceHierarchy.xsd
              example: !include examples/xml_files/beaconPlaceHierarchy.xml

