#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/1f8ba58d-facd-4220-9e73-4391ce6335f8 # 
title: Beacon Process API
version: v1
types:
  beacon: !include resourceTypes/beacon.raml
  beaconType: !include resourceTypes/beacon_type.raml
  beaconHierarchy: !include resourceTypes/beacon_hierarchy.raml
  beaconPlaceHierarchyUpdate: !include resourceTypes/beacon_place_hierarchy_put.raml
  beaconPlaceHierarchies: !include resourceTypes/beacon_place_hierarchy.raml
/beacons:
  get:
    description: Get All Beacon from every Organization
    responses:
      200:
        body:
          application/json:
            type: beacon[]
            example: !include examples/json_files/beacons.json
  /{id_organization}:
    get: 
      description: Get All Beacons by Organiztion
      responses: 
        200:
          body: 
            application/json:
              type: beacon[]
              example: !include examples/json_files/beacons.json
    post:
      description: Register a new Beacon to a Organization
      body: 
        application/json:
          type: beacon
          example: !include examples/json_files/beacon.json
    /{id_beacon}:
      get:
        description: Get a Beacon
        responses:
          200:
            body:
              application/json:
                type: beacon
                example: !include examples/json_files/beacon.json
      put:
        description: Update a Beacon
        body:
          application/json:
            type: beacon
            example: !include examples/json_files/beacon.json
    /type:
      get:
        description: Get All Beacons Types
        responses:
          200:
            body:
              application/json:
                type: beaconType[]
      post:
        description: Register a Beacon Type
        body:
          application/json:
            type: beaconType
            example: !include examples/json_files/beaconType.json
      /{id_beacon_type}:
        get:
          description: Get a Beacon Type
          responses:
            200:
              body:
                application/json:
                  type: beaconType
                  example: !include examples/json_files/beaconType.json
        put:
          description: Update a Beacon Type
          body:
            application/json:
              type: beaconType
              example: !include examples/json_files/beaconType.json
    /hierarchy:
      post:
        description: Register a Beacon Type
        body:
          application/json:
            type: beaconHierarchy
            example: !include examples/json_files/beaconHierarchy.json
      get:
        description: Get All Beacons Hierarchies
        responses:
          200:
            body:
              application/json:
                type: beaconHierarchy[]
                example: !include examples/json_files/beaconHierarchies.json
      /{id_beacon_hierarchy}:
        get:
          description: Get a Beacon Hierarchy
          responses:
            200:
              body:
                application/json:
                  type: beaconHierarchy[]
                  example: !include examples/json_files/beaconHierarchies.json
        put:
          description: Update a Beacon Hierarchy
          body:
            application/json:
              type: beaconHierarchy
              example: !include examples/json_files/beaconHierarchy.json
          responses:
            200:
              body:
                application/json:
    /place_hierarchy:
      get:
        description: Get All Beacons Place Hierarchy
        responses:
          200:
            body:
              application/json:
                type: beaconPlaceHierarchies[]
                example: !include examples/json_files/beaconsPlaceHierarchies.json
      /{id_beacon_place_hierarchy}:
        put:
          description: Update a Beacon Place Hierarchy
          body:
            application/json:
              type: beaconPlaceHierarchyUpdate
              example: !include examples/json_files/beaconPlaceHierarchy.json    

